### ISSUE TITLE
link to "Think Python" broken

### ISSUE THREAD

**Issue by PeterVermont** [waddell/urban-informatics-and-visualization#2]
On the main README.md the link is:
`
http://www.greenteapress.com/thinkpython/.%C2%A0This`

instead of:

`http://www.greenteapress.com/thinkpython`

**Comment by PeterVermont** [comment]
Actually may as well link to newer edition: [http://greenteapress.com/wp/think-python-2e/](http://greenteapress.com/wp/think-python-2e/)

**Comment by waddell** [comment]
Fixed. Thanks.
